-- Load remaining visa types from the complete dataset
-- Continue with the rest of the visa categories

INSERT INTO BaseVisaTypes (Id, Code, Name, Description, Question1, Question2, Question3, VisaName, VisaDescription, VisaAppropriateFor, Status, CreatedAt, UpdatedAt, ConfidenceScore)
VALUES
-- G Category (International Organizations)
(NEWID(), 'G-1', 'G-1 Int''l Organization / UN Rep', 'For principal resident representative of recognized foreign governments to international organizations and families.', 'Are you assigned by a foreign government to an international organization in the U.S.?', NULL, NULL, 'G-1', 'For principal resident representative of recognized foreign governments to international organizations and families.', 'International org representatives', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),
(NEWID(), 'G-2', 'G-2 Int''l Organization Representative', 'For other representatives of member governments to international organizations and families.', 'Are you a representative of a foreign government accredited to an international organization?', NULL, NULL, 'G-2', 'For other representatives of member governments to international organizations and families.', 'Government representatives', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),
(NEWID(), 'G-3', 'G-3 Non-member Gov''t Rep', 'For representatives of non-recognized foreign governments to international organizations and families.', 'Are you accredited by a non-recognized foreign government to an international organization?', NULL, NULL, 'G-3', 'For representatives of non-recognized foreign governments to international organizations and families.', 'Non-member government reps', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),
(NEWID(), 'G-4', 'G-4 Int''l Org Officer or Employee', 'For officers or employees of international organizations and immediate family.', 'Are you an official of an international organization in the U.S.?', NULL, NULL, 'G-4', 'For officers or employees of international organizations and immediate family.', 'International org employees', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),
(NEWID(), 'G-5', 'G-5 Attendant / Servant', 'For attendants, servants, and personal employees of G-1 through G-4 visa holders.', 'Are you employed by someone holding a G-category visa as attendant or servant?', NULL, NULL, 'G-5', 'For attendants, servants, and personal employees of G-1 through G-4 visa holders.', 'Service personnel', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),

-- NATO Category
(NEWID(), 'NATO-1', 'NATO-1 Representative', 'For principal permanent representative of member state to NATO.', 'Are you a permanent representative of a NATO member state in the U.S.?', NULL, NULL, 'NATO-1', 'For principal permanent representative of member state to NATO.', 'NATO representatives', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),
(NEWID(), 'NATO-2', 'NATO-2 Official Representative', 'For other representatives of NATO member states.', 'Are you an official from a NATO member state accredited to NATO in the U.S.?', NULL, NULL, 'NATO-2', 'For other representatives of NATO member states.', 'NATO officials', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),
(NEWID(), 'NATO-3', 'NATO-3 Clerical Staff', 'For clerical staff accompanying NATO-1/2 representatives.', 'Are you clerical support accompanying a NATO representative in the U.S.?', NULL, NULL, 'NATO-3', 'For clerical staff accompanying NATO-1/2 representatives.', 'NATO clerical staff', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),
(NEWID(), 'NATO-4', 'NATO-4 Official of NATO', 'For other officials of NATO not in NATO-1 classification.', 'Are you an official of NATO (not classified as NATO-1) present in the U.S.?', NULL, NULL, 'NATO-4', 'For other officials of NATO not in NATO-1 classification.', 'NATO officials', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),
(NEWID(), 'NATO-5', 'NATO-5 Expert Employee', 'Experts employed on missions on behalf of NATO and dependents.', 'Are you a NATO-employed expert or your dependent in support of NATO missions?', NULL, NULL, 'NATO-5', 'Experts employed on missions on behalf of NATO and dependents.', 'NATO experts', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),
(NEWID(), 'NATO-6', 'NATO-6 Civilian Component Member', 'Civilian components attached to allied military headquarters in U.S.', 'Are you civilian staff assigned under NATO Status-of-Forces to U.S. headquarters?', NULL, NULL, 'NATO-6', 'Civilian components attached to allied military headquarters in U.S.', 'NATO civilian staff', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),
(NEWID(), 'NATO-7', 'NATO-7 Attendant/Servant', 'Attendants or servants of NATO-1 through NATO-6 members.', 'Are you employed as attendant or servant by a NATO-category visa holder?', NULL, NULL, 'NATO-7', 'Attendants or servants of NATO-1 through NATO-6 members.', 'NATO service personnel', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),

-- O Category (Extraordinary Ability)
(NEWID(), 'O-1', 'O-1 Extraordinary Ability', 'For individuals with extraordinary ability in sciences, arts, business, athletics, or motion picture/TV.', 'Can you show sustained national or international acclaim (e.g. major award or evidence meeting at least 3 criteria)?', NULL, NULL, 'O-1', 'For individuals with extraordinary ability in sciences, arts, business, athletics, or motion picture/TV.', 'Extraordinary ability', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),
(NEWID(), 'O-2', 'O-2 Support Staff', 'For assistants accompanying O-1 performers or athletes, essential to performance.', 'Are you essential to support an O-1 visa holder''s performance or event?', NULL, NULL, 'O-2', 'For assistants accompanying O-1 performers or athletes, essential to performance.', 'O-1 support staff', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),
(NEWID(), 'O-3', 'O-3 Spouse/Child', 'For spouse and children of O-1 or O-2 visa holders.', 'Are you the spouse or child of an O-1 or O-2 visa holder?', NULL, NULL, 'O-3', 'For spouse and children of O-1 or O-2 visa holders.', 'O category dependents', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),

-- P Category (Performers)
(NEWID(), 'P-1', 'P-1 Athlete/Entertainment Group', 'For internationally recognized athletes or entertainment groups.', 'Are you an internationally recognized athlete or part of an entertainment group?', NULL, NULL, 'P-1', 'For internationally recognized athletes or entertainment groups.', 'Athletes and entertainers', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),
(NEWID(), 'P-2', 'P-2 Artist Exchange', 'For artists or entertainers in reciprocal exchange programs.', 'Are you participating in a reciprocal exchange program as an artist or entertainer?', NULL, NULL, 'P-2', 'For artists or entertainers in reciprocal exchange programs.', 'Exchange artists', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),
(NEWID(), 'P-3', 'P-3 Culturally Unique Program', 'For artists/entertainers in culturally unique programs.', 'Is your performance part of a culturally unique program recognized by U.S. authorities?', NULL, NULL, 'P-3', 'For artists/entertainers in culturally unique programs.', 'Cultural performers', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),
(NEWID(), 'P-4', 'P-4 Spouse/Child', 'For spouse or child of P-1, P-2, or P-3 visa holders.', 'Are you the spouse or child of a P-category visa holder?', NULL, NULL, 'P-4', 'For spouse or child of P-1, P-2, or P-3 visa holders.', 'P category dependents', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),

-- Q, R Categories
(NEWID(), 'Q-1', 'Q-1 Cultural Exchange', 'For participants in international cultural exchange programs or events.', 'Are you part of a CDC-designated cultural exchange program for practical experience?', NULL, NULL, 'Q-1', 'For participants in international cultural exchange programs or events.', 'Cultural exchange participants', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),
(NEWID(), 'R-1', 'R-1 Religious Worker', 'For individuals working in a religious occupation with a nonprofit religious organization.', 'Are you coming to work in a religious vocation or occupation for a nonprofit religious organization?', 'Are you a minister or religious worker with at least two years membership in the organization?', NULL, 'R-1', 'For individuals working in a religious occupation with a nonprofit religious organization.', 'Religious workers', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),
(NEWID(), 'R-2', 'R-2 Dependent', 'For spouse or child of R-1 religious worker.', 'Are you the spouse or child of an R-1 visa holder?', NULL, NULL, 'R-2', 'For spouse or child of R-1 religious worker.', 'Religious worker dependents', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),

-- S Category (Informants)
(NEWID(), 'S-5', 'S-5 Informant Visa (Criminal)', 'For informants with credible information regarding criminal activity.', 'Do you possess credible information regarding criminal activity and are you assisting U.S. law enforcement?', NULL, NULL, 'S-5', 'For informants with credible information regarding criminal activity.', 'Criminal informants', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),
(NEWID(), 'S-6', 'S-6 Informant Visa (Terrorism)', 'For informants regarding terrorism or national security matters.', 'Do you have credible information about terrorism and intend to help U.S. authorities?', NULL, NULL, 'S-6', 'For informants regarding terrorism or national security matters.', 'Terrorism informants', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),
(NEWID(), 'S-7', 'S-7 Family of S-5 or S-6', 'For spouse, unmarried child, or parent of S-5 or S-6 visa holders.', 'Are you a qualifying relative (spouse, child, or parent) of an S-5 or S-6 visa holder?', NULL, NULL, 'S-7', 'For spouse, unmarried child, or parent of S-5 or S-6 visa holders.', 'Informant families', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),

-- T Category (Trafficking Victims)
(NEWID(), 'T-1', 'T-1 Victim of Human Trafficking', 'For victims of severe trafficking who assist law enforcement.', 'Were you a victim of a severe form of human trafficking (sex or labor)?', 'Are you in the U.S. because of that trafficking?', 'Can you comply with reasonable requests from law enforcement (unless trauma exception applies)?', 'T-1', 'For victims of severe trafficking who assist law enforcement.', 'Trafficking victims', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),
(NEWID(), 'T-2', 'T-2 Spouse of T-1', 'For spouses of principal T-1 applicants.', 'Are you married to a T-1 principal applicant?', NULL, NULL, 'T-2', 'For spouses of principal T-1 applicants.', 'T-1 spouses', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),
(NEWID(), 'T-3', 'T-3 Child of T-1', 'For children of principal T-1 applicants.', 'Are you an unmarried child of a T-1 principal applicant?', NULL, NULL, 'T-3', 'For children of principal T-1 applicants.', 'T-1 children', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),
(NEWID(), 'T-4', 'T-4 Parent of T-1', 'For parents of T-1 principal applicants (if child under 21).', 'Are you a parent of a T-1 principal applicant under 21 years old?', NULL, NULL, 'T-4', 'For parents of T-1 principal applicants (if child under 21).', 'T-1 parents', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),

-- U Category (Crime Victims)
(NEWID(), 'U-1', 'U-1 Victim of Criminal Activity', 'For victims of qualifying crimes who assist law enforcement.', 'Were you a victim of a qualifying crime in the U.S.?', 'Have you suffered substantial physical or mental abuse?', 'Are you or likely to be helpful to law enforcement in investigating or prosecuting the crime?', 'U-1', 'For victims of qualifying crimes who assist law enforcement.', 'Crime victims', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),
(NEWID(), 'U-2', 'U-2 Spouse of U-1', 'For spouses of principal U-1 applicants.', 'Are you married to a U-1 principal applicant?', NULL, NULL, 'U-2', 'For spouses of principal U-1 applicants.', 'U-1 spouses', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),
(NEWID(), 'U-3', 'U-3 Child of U-1', 'For children of principal U-1 applicants.', 'Are you an unmarried child under 21 of a U-1 principal applicant?', NULL, NULL, 'U-3', 'For children of principal U-1 applicants.', 'U-1 children', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),
(NEWID(), 'U-4', 'U-4 Parent of U-1', 'For parents of U-1 principal applicants (if child under 21).', 'Are you the parent of a U-1 principal applicant under 21?', NULL, NULL, 'U-4', 'For parents of U-1 principal applicants (if child under 21).', 'U-1 parents', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),
(NEWID(), 'U-5', 'U-5 Sibling of U-1', 'For minor unmarried siblings of U-1 applicants.', 'Are you an unmarried sibling under 21 of a U-1 principal applicant?', NULL, NULL, 'U-5', 'For minor unmarried siblings of U-1 applicants.', 'U-1 siblings', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),

-- V Category (Family-based)
(NEWID(), 'V-1', 'V-1 Spouse of LPR', 'For spouses of lawful permanent residents with family petitions filed before Dec 21, 2000.', 'Is your spouse a lawful permanent resident with an I-130 petition filed before December 21, 2000?', 'Has that petition been pending at least three years?', NULL, 'V-1', 'For spouses of lawful permanent residents with family petitions filed before Dec 21, 2000.', 'LPR spouses', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),
(NEWID(), 'V-2', 'V-2 Child of LPR', 'For unmarried children of LPRs with qualifying petitions filed before cutoff date.', 'Are you an unmarried child of an LPR with a qualifying petition filed before Dec 21, 2000?', 'Has that petition been pending at least three years?', NULL, 'V-2', 'For unmarried children of LPRs with qualifying petitions filed before cutoff date.', 'LPR children', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),

-- Special Categories
(NEWID(), 'TN', 'TN NAFTA / USMCA Professional', 'For Canadian and Mexican professionals under USMCA agreement.', 'Are you a Canadian or Mexican citizen with a job offer in a qualifying profession?', 'Do you have the required credentials or licensure for that profession?', NULL, 'TN', 'For Canadian and Mexican professionals under USMCA agreement.', 'NAFTA professionals', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),
(NEWID(), 'TPS', 'Temporary Protected Status (TPS)', 'For nationals of designated countries who cannot safely return due to conditions in their home country.', 'Is your nationality from a country designated for TPS?', 'Are you continuously residing in the U.S. since the TPS designation date?', NULL, 'TPS', 'For nationals of designated countries who cannot safely return due to conditions in their home country.', 'Protected status', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0);

PRINT 'Loaded additional 40+ visa types...';

-- Now add immigrant visa categories
INSERT INTO BaseVisaTypes (Id, Code, Name, Description, Question1, Question2, Question3, VisaName, VisaDescription, VisaAppropriateFor, Status, CreatedAt, UpdatedAt, ConfidenceScore)
VALUES
-- Immediate Relative Categories
(NEWID(), 'IR-1', 'IR-1 Spouse of U.S. Citizen', 'Immediate relative immigrant visa for spouse of a U.S. citizen.', 'Are you legally married to a U.S. citizen?', 'Was your marriage bona fide and not solely for immigration purposes?', NULL, 'IR-1', 'Immediate relative immigrant visa for spouse of a U.S. citizen.', 'USC spouses', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),
(NEWID(), 'IR-2', 'IR-2 Child of U.S. Citizen', 'Immediate relative immigrant visa for unmarried child of U.S. citizen.', 'Are you unmarried and under 21 and the child of a U.S. citizen?', NULL, NULL, 'IR-2', 'Immediate relative immigrant visa for unmarried child of U.S. citizen.', 'USC children', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),
(NEWID(), 'CR-1', 'CR-1 Conditional Spouse', 'Conditional permanent resident visa for spouses married less than two years.', 'Were you married for less than two years at time of admission on immigrant petition?', 'Is your marriage bona fide?', NULL, 'CR-1', 'Conditional permanent resident visa for spouses married less than two years.', 'Conditional spouses', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),
(NEWID(), 'IR-5', 'IR-5 Parent of U.S. Citizen', 'Immediate relative immigrant visa for parent of U.S. citizen (21+).', 'Is your child a U.S. citizen who is at least 21 years old?', NULL, NULL, 'IR-5', 'Immediate relative immigrant visa for parent of U.S. citizen (21+).', 'USC parents', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),

-- Employment-Based Categories
(NEWID(), 'EB-1A', 'EB-1 Extraordinary Ability (Immigrant)', 'Employment-based first preference for persons of extraordinary ability.', 'Can you demonstrate sustained national or international acclaim in your field?', 'Do you meet at least three of the regulatory criteria for extraordinary ability?', NULL, 'EB-1A', 'Employment-based first preference for persons of extraordinary ability.', 'Extraordinary ability (immigrant)', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),
(NEWID(), 'EB-1B', 'EB-1 Outstanding Professor/Researcher', 'Employment-based first preference for outstanding professors or researchers.', 'Do you have at least three years of experience teaching or research?', 'Are you recognized internationally or widely in your academic field?', NULL, 'EB-1B', 'Employment-based first preference for outstanding professors or researchers.', 'Outstanding professors', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),
(NEWID(), 'EB-1C', 'EB-1 Multinational Executive or Manager', 'Employment-based first preference for managers or executives transferred within multinational companies.', 'Have you worked for the same employer abroad for at least one year in last three?', 'Will you work in a managerial or executive capacity in the U.S. entity?', NULL, 'EB-1C', 'Employment-based first preference for managers or executives transferred within multinational companies.', 'Multinational executives', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),
(NEWID(), 'EB-2', 'EB-2 Advanced Degree / Exceptional Ability', 'Employment-based second preference for advanced degree holders or persons with exceptional ability.', 'Do you have an advanced degree (master''s or higher) or equivalent experience?', 'Do you possess exceptional ability in sciences, arts, or business above normal?', NULL, 'EB-2', 'Employment-based second preference for advanced degree holders or persons with exceptional ability.', 'Advanced degree holders', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),
(NEWID(), 'EB-3', 'EB-3 Professional / Skilled / Other Worker', 'Employment-based third preference for degree professionals, skilled workers and other workers.', 'Are you a professional with a bachelor''s degree or a skilled worker with at least 2 years training?', 'Is there a permanent, full-time job offer from a U.S. employer?', NULL, 'EB-3', 'Employment-based third preference for degree professionals, skilled workers and other workers.', 'Skilled workers', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),
(NEWID(), 'EB-4', 'EB-4 Special Immigrant', 'Special immigrant classification for religious workers, broadcasters, certain employees of U.S. foreign service.', 'Are you a qualifying religious worker, broadcaster, or special immigrant under EB-4 classification?', NULL, NULL, 'EB-4', 'Special immigrant classification for religious workers, broadcasters, certain employees of U.S. foreign service.', 'Special immigrants', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),
(NEWID(), 'EB-5', 'EB-5 Immigrant Investor', 'Employment-based fifth preference for investors making qualifying investment and job creation.', 'Are you investing the required amount ($1.05 M or $800K in targeted area)?', 'Will the investment create at least 10 full-time U.S. jobs?', NULL, 'EB-5', 'Employment-based fifth preference for investors making qualifying investment and job creation.', 'Immigrant investors', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),

-- Diversity and Special Categories
(NEWID(), 'DV-1', 'Diversity Immigrant (DV-1)', 'Immigrant visa under Diversity Visa Program lottery.', 'Did you win the Diversity Visa lottery and qualify under education or work experience requirements?', NULL, NULL, 'DV-1', 'Immigrant visa under Diversity Visa Program lottery.', 'Diversity visa winners', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),
(NEWID(), 'SIJS', 'Special Immigrant Juvenile Status', 'Youth declared dependent by juvenile court and unable to reunite with one or both parents.', 'Are you declared dependent under a juvenile court for abuse, neglect, or abandonment?', 'Is reunification with one or both parents not viable due to abuse, neglect or abandonment?', NULL, 'SIJS', 'Youth declared dependent by juvenile court and unable to reunite with one or both parents.', 'Juvenile immigrants', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),
(NEWID(), 'VAWA', 'VAWA Self-Petitioner', 'Self-petitioning abused spouse, child or parent under Violence Against Women Act.', 'Have you been subjected to battery or extreme cruelty by U.S. citizen or LPR relative?', 'Is your abuser a U.S. citizen or lawful permanent resident?', 'Can you demonstrate eligibility to self-petition without their knowledge or consent?', 'VAWA', 'Self-petitioning abused spouse, child or parent under Violence Against Women Act.', 'Abuse victims', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0),
(NEWID(), 'SIV', 'Special Immigrant Visa (SIV)', 'For certain Iraqi or Afghan nationals who worked with U.S. Government or military.', 'Did you work for or on behalf of the U.S. government in Iraq or Afghanistan?', 'Have you met service eligibility, security, and documentation requirements?', NULL, 'SIV', 'For certain Iraqi or Afghan nationals who worked with U.S. Government or military.', 'Iraq/Afghanistan translators', 'Active', GETUTCDATE(), GETUTCDATE(), 1.0);

PRINT 'Loaded immigrant and special visa categories...';

-- Verify final count
SELECT COUNT(*) AS TotalVisaTypes FROM BaseVisaTypes;
PRINT 'All visa types loaded successfully!';